
spring.application.name=Veterinaria

spring.datasource.url=jdbc:postgresql://aws-0-us-west-2.pooler.supabase.com:6543/postgres
spring.datasource.username=postgres.azflakudttnpxbbhoiqy
spring.datasource.password=M!jPY+5Y7e.F!i%
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

