# nombre del proyecto
spring.application.name=Veterinaria
# conector - puerto - base de datos
spring.datasource.url=jdbc:mysql://localhost:3310/Veterinaria
# usuario
spring.datasource.username=root
# password
spring.datasource.password=1234
# driver de conexión con MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# dialecto de Hibernate
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
# create: borra y crea todo cada vez
# update: actualiza sin borrar
spring.jpa.hibernate.ddl-auto=update
# mostrar SQL en consola
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true